/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import static Model.Senha_DAO.SenhaConvencional;
import static Model.Senha_DAO.atendente;
import static Model.Senha_DAO.atendente02;
import static Model.Senha_DAO.total;
import static Model.Senha_DAO.total02;

/**
 *
 * @author JEFFERSON
 */
public class Inicio_GUI extends javax.swing.JFrame {
    
   public static String resultado = "";
    String balcaoconv = "";
    String acumula = "";
    String acumula02 = "";
    String balcaopref = "";

    /**
     * Creates new form Inicio_GUI
     */
    public Inicio_GUI() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        Imprimir = new javax.swing.JButton();
        preferencial = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        GuichePref = new javax.swing.JTextField();
        SenhaPref = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        GuicheConv = new javax.swing.JTextField();
        SenhaConv = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        AcumulaPref = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        AcumulaConv = new javax.swing.JTextArea();
        convencional = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(51, 115, 83));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(0, 153, 255));
        jPanel2.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("PAINEL GERADOR DE SENHA");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(110, 30, 610, 30);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 800, 90);

        Imprimir.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        Imprimir.setForeground(new java.awt.Color(126, 0, 0));
        Imprimir.setText("IMPRIMIR");
        Imprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ImprimirActionPerformed(evt);
            }
        });
        jPanel1.add(Imprimir);
        Imprimir.setBounds(320, 430, 170, 50);

        preferencial.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        preferencial.setForeground(new java.awt.Color(0, 178, 114));
        preferencial.setText("PREFERENCIAL");
        preferencial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                preferencialActionPerformed(evt);
            }
        });
        jPanel1.add(preferencial);
        preferencial.setBounds(620, 430, 160, 50);

        jPanel3.setBackground(new java.awt.Color(0, 178, 114));

        GuichePref.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        GuichePref.setForeground(new java.awt.Color(0, 143, 64));
        GuichePref.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        GuichePref.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuichePrefActionPerformed(evt);
            }
        });

        SenhaPref.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        SenhaPref.setForeground(new java.awt.Color(0, 143, 64));
        SenhaPref.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        SenhaPref.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SenhaPrefActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Preferencial");

        jLabel6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Guichê");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))))
            .addComponent(SenhaPref, javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(GuichePref, javax.swing.GroupLayout.Alignment.LEADING)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(5, 5, 5)
                .addComponent(SenhaPref, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(GuichePref, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(271, 271, 271))
        );

        jPanel1.add(jPanel3);
        jPanel3.setBounds(440, 120, 170, 280);

        jPanel4.setBackground(new java.awt.Color(51, 90, 228));

        GuicheConv.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        GuicheConv.setForeground(new java.awt.Color(0, 51, 255));
        GuicheConv.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        GuicheConv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuicheConvActionPerformed(evt);
            }
        });

        SenhaConv.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        SenhaConv.setForeground(new java.awt.Color(0, 51, 255));
        SenhaConv.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        SenhaConv.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        SenhaConv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SenhaConvActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Convencional");

        jLabel9.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Guichê");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addComponent(SenhaConv, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(GuicheConv)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SenhaConv, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(GuicheConv, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel4);
        jPanel4.setBounds(20, 120, 170, 280);

        AcumulaPref.setColumns(20);
        AcumulaPref.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        AcumulaPref.setForeground(new java.awt.Color(0, 143, 64));
        AcumulaPref.setRows(5);
        jScrollPane1.setViewportView(AcumulaPref);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(620, 120, 160, 280);

        AcumulaConv.setColumns(20);
        AcumulaConv.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        AcumulaConv.setForeground(new java.awt.Color(0, 51, 255));
        AcumulaConv.setRows(5);
        jScrollPane2.setViewportView(AcumulaConv);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(200, 120, 166, 280);

        convencional.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        convencional.setForeground(new java.awt.Color(51, 90, 228));
        convencional.setText("CONVENCIONAL");
        convencional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                convencionalActionPerformed(evt);
            }
        });
        jPanel1.add(convencional);
        convencional.setBounds(20, 430, 170, 50);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 792, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ImprimirActionPerformed
        Model.ImprimirSenha.imprimir();
        
    }//GEN-LAST:event_ImprimirActionPerformed

    private void preferencialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_preferencialActionPerformed
        Model.Senha_DAO.SenhaPreferencial();
        String p = "P";
        String guiche02 = "";
        resultado = p + total02;
        balcaopref = guiche02 + atendente02;
        acumula02 += resultado + " Guichê - " + balcaopref + "\n" ;
        
        SenhaPref.setText(String.valueOf(resultado));
        GuichePref.setText(String.valueOf(balcaopref));
        AcumulaPref.setText(String.valueOf(acumula02));
    }//GEN-LAST:event_preferencialActionPerformed

    private void GuichePrefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuichePrefActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GuichePrefActionPerformed

    private void GuicheConvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuicheConvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GuicheConvActionPerformed

    private void SenhaConvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SenhaConvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SenhaConvActionPerformed

    private void SenhaPrefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SenhaPrefActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SenhaPrefActionPerformed

    private void convencionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_convencionalActionPerformed
        // TODO add your handling code here:
        Model.Senha_DAO.SenhaConvencional();
        String c = "C";
        String guiche01 = "";
        resultado =  c + total;
        balcaoconv = guiche01 + atendente;
        acumula +=  resultado + " Guichê - " + balcaoconv + "\n";
        
        SenhaConv.setText(String.valueOf(resultado));
        GuicheConv.setText(String.valueOf(balcaoconv));
        AcumulaConv.setText(String.valueOf( acumula));
    }//GEN-LAST:event_convencionalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio_GUI().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea AcumulaConv;
    private javax.swing.JTextArea AcumulaPref;
    private javax.swing.JTextField GuicheConv;
    private javax.swing.JTextField GuichePref;
    private javax.swing.JButton Imprimir;
    private javax.swing.JTextField SenhaConv;
    private javax.swing.JTextField SenhaPref;
    private javax.swing.JButton convencional;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton preferencial;
    // End of variables declaration//GEN-END:variables
}
